<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NicheImageRipper.SiteModules</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.WebUtilities">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\10.0.7\Microsoft.AspNetCore.WebUtilities.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
