<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
<!--        <UseWPF>true</UseWPF>-->
        <DefineConstants>WINDOWS</DefineConstants>
    </PropertyGroup>
<!--    <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-windows'">-->
<!--        <UseWPF>true</UseWPF>-->
<!--        <DefineConstants>WINDOWS</DefineConstants>-->
<!--    </PropertyGroup>-->

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.14" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Tmds.DBus.Protocol" Version="0.92.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
      <ProjectReference Include="..\Service\Service.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\Full\" />
      <Folder Include="Models\Thin\Data\" />
    </ItemGroup>
</Project>
