<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>NicheImageRipper.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.79" />
      <PackageReference Include="Gkmo.Google.Apis.PhotosLibrary.v1" Version="1.36.1.1471" />
      <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3783" />
      <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
      <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.15.0" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
      <PackageReference Include="Selenium.WebDriver" Version="4.46.0" />
      <PackageReference Include="Selenium.WebDriver.GeckoDriver" Version="0.37.1" />
      <PackageReference Include="Serilog" Version="4.4.0" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
      <PackageReference Include="SharpCompress" Version="0.50.0" />
      <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.4" />
      <PackageReference Include="System.Data.SQLite" Version="2.0.3" />
      <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
      <ProjectReference Include="..\CSWebDriverClient\CSWebDriverClient.csproj" />
      <ProjectReference Include="..\FlareSolverrIntegration\FlareSolverrIntegration.csproj" />
      <ProjectReference Include="..\ImpersonateClient\ImpersonateClient.csproj" />
      <ProjectReference Include="..\IwaraApiClient\IwaraApiClient.csproj" />
      <ProjectReference Include="..\MangaDexLibrary\MangaDexLibrary.csproj" />
      <ProjectReference Include="..\PixivApi\PixivApi.csproj" />
      <ProjectReference Include="..\SteamApiClient\SteamApiClient.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.WebUtilities">
        <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\10.0.7\Microsoft.AspNetCore.WebUtilities.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\SiteModules\bin\$(Configuration)\net10.0\SiteModules.dll">
<!--            <Link>Plugins\SiteModules.dll</Link>-->
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
