<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
      <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
      <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.16.0" />
      <PackageReference Include="Selenium.WebDriver" Version="4.46.0" />
      <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CSWebDriverClient\CSWebDriverClient.csproj" />
      <ProjectReference Include="..\FlareSolverrIntegration\FlareSolverrIntegration.csproj" />
    </ItemGroup>

</Project>
