name: Update Wiki
on: 
  push:
    branches:    
        - 'main'
jobs:
  update_wiki:
    runs-on: ubuntu-latest
    env:
      EMAIL: 52053026+Exiua@users.noreply.github.com
      USER: Exiua
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@main
      - name: Clone Wiki Repo
        run: cd .. && git clone https://github.com/Exiua/NicheImageRipper.wiki.git && cd NicheImageRipper
      - name: Run wiki_page_formatter
        run: python3 ./Util/wiki_page_formatter.py -uo "../NicheImageRipper.wiki/Supported-Sites.md"
      - name: Commit Wiki Changes
        run: cd ../NicheImageRipper.wiki && git config user.name ${USER} && git config user.email ${EMAIL} && cat Supported-Sites.md && git commit -am "Updated Supported Sites"
      - name: Push Wiki Changes
        run: git push https://${GH_PAT}@github.com/Exiua/NicheImageRipper.wiki.git
