name: Update Wiki
on: 
  push:
    branches:    
        - 'main'
jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Clone Wiki Repo
        run: git clone https://github.com/Exiua/NicheImageRipper.wiki.git
      - name: Run wiki_page_formatter
        run: python3 ./Util/wiki_page_formatter.py -uo "./NicheImageRipper.wiki/Supported-Sites.md"
      - name: Update Supported Sites Wiki Page
        run: cp ./Util/Supported-Sites.md ./NicheImageRipper.wiki/Supported-Sites.md && cat ./NicheImageRipper.wiki/Supported-Sites.md
      - name: Push Wiki Changes
        env:
          EMAIL: 52053026+Exiua@users.noreply.github.com
          USER: Exiua
          GH_PAT: ${{ secrets.GH_PAT }}
        run: cd NicheImageRipper.wiki && git config user.name ${USER} && git config user.email ${EMAIL} && git commit -am "Updated Wiki" && git push https://${GH_PAT}@github.com/Exiua/NicheImageRipper.wiki.git